/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.medac.Interfaces;

import es.medac.ProyectoInterfaces.Logging;
import javax.swing.JOptionPane;

/**
 *
 * @author ps4ju
 */
public class Loggin extends javax.swing.JFrame {

    /**
     * Creates new form Loggin
     */
    public Loggin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre_campo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        boton_acceder = new javax.swing.JButton();
        contraseña_campo = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombre_campo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_campoActionPerformed(evt);
            }
        });
        getContentPane().add(nombre_campo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 90, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        boton_acceder.setBackground(new java.awt.Color(255, 210, 174));
        boton_acceder.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        boton_acceder.setText("Acceder");
        boton_acceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_accederActionPerformed(evt);
            }
        });
        getContentPane().add(boton_acceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 100, 30));
        getContentPane().add(contraseña_campo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 90, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/medac/Interfaces/Medac_Foto.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, 100));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/medac/Interfaces/fondo-futurista-degradado-geometrico_23-2149116406 (1).jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombre_campoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_campoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_campoActionPerformed

    private void boton_accederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_accederActionPerformed
        //Creamos el objeto de lg de la clase Logging
        Logging lg = new Logging();
        //El titulo y el mensaje de la ventana emergente de error
        String mensaje = "Contraseña Incorrecta";
        String titulo = "Error";
        //Si el nombre y la contraseña son correctos, entrará en el programa, sino, saltará la ventana emergente
        if(!lg.logging_usuario(nombre_campo.getText(), contraseña_campo.getText()).equals("Log Incorrecto")){
            this.setVisible(false);
            Menu m = new Menu();
            m.setVisible(true); 
        }else{
            JOptionPane.showMessageDialog(this,
        mensaje,
        titulo,
        JOptionPane.ERROR_MESSAGE);
            
        }
        
    }//GEN-LAST:event_boton_accederActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loggin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton boton_acceder;
    private javax.swing.JPasswordField contraseña_campo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nombre_campo;
    // End of variables declaration//GEN-END:variables
}
